# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '__first__'),
        ('molho', '0001_initial'),
        ('propriedade', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('dataInicio', models.DateTimeField()),
                ('dataFim', models.DateTimeField()),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('autorizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='pessoa.Pessoa')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propriedade.Propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molho.Chave')),
                ('conferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa')),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molho.Controle')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('dataRetirada', models.DateTimeField()),
                ('dataDevolucao', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('autorizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorizacao.Autorizacao')),
                ('autorizadoPor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregue_por', to='pessoa.Pessoa')),
                ('molho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molho.Molho')),
                ('recebidoPor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebido_por', to='pessoa.Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='confirmacao',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorizacao.Registro'),
        ),
    ]
