# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefoneComercial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone Comercial')),
                ('telefoneResidencial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone Residencial')),
                ('celular1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Celular 1')),
                ('celular2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Celular 2')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
