# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefoneComercial', models.CharField(max_length=100, verbose_name='Telefone Comercial')),
                ('telefoneResidencial', models.CharField(max_length=100, verbose_name='Telefone Residencial')),
                ('celular1', models.CharField(max_length=100, verbose_name='Celular 1')),
                ('celular2', models.CharField(max_length=100, verbose_name='Celular 2')),
                ('numeroEndereco', models.PositiveIntegerField(verbose_name='Numero do Endereço')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=150)),
                ('complemento', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
