# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(max_length=30, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='complemento',
            field=models.CharField(max_length=150, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='logradouro',
            field=models.CharField(max_length=150, verbose_name='Logradouro'),
        ),
    ]
