# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20180110_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='numeroEndereco',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
