# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molho',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Em Uso'), (1, 'Devolvido'), (2, 'Alerta'), (3, 'Perdido')], default=1, verbose_name='Status do Molho'),
        ),
    ]
