# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molho', '0002_auto_20180417_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='molho',
            name='observacao',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
