# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('chaves', models.IntegerField(verbose_name='Quantidade de Chaves')),
                ('controles', models.IntegerField(verbose_name='Quantidade de Controle')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Em Uso'), (1, 'Devolvido'), (2, 'Alerta'), (3, 'Perdido')], null=True, verbose_name='Status do Molho')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propriedade.Propriedade')),
            ],
        ),
    ]
