# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dataPrevisaoRetorno',
            field=models.DateTimeField(verbose_name='Previsão do Retorno'),
        ),
    ]
