# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20180417_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dataEntrega',
            field=models.DateTimeField(verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='dataRetorno',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Retorno'),
        ),
    ]
