# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20180418_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
