# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20180418_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='observacao',
        ),
    ]
