# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('tipoPropriedade', models.IntegerField(choices=[(0, ''), (1, 'Apartamento'), (2, 'Casa'), (3, 'Comercio')], default=0, verbose_name='Tipo Propriedade')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=150)),
                ('complemento', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa')),
            ],
        ),
    ]
