# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedade', '0003_auto_20180110_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='tipoPropriedade',
            field=models.IntegerField(choices=[(1, 'Apartamento'), (2, 'Casa'), (3, 'Comercio')], default=1, verbose_name='Tipo Propriedade'),
        ),
    ]
