# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('molho', '0001_initial'),
        ('pessoa', '0001_initial'),
        ('propriedade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrega', models.DateTimeField(verbose_name='Data Entrega')),
                ('dataPrevisaoRetorno', models.DateTimeField(verbose_name='Data de Previsão do Retorno')),
                ('dataRetorno', models.DateTimeField(verbose_name='Data Retorno')),
                ('molhos', models.ManyToManyField(to='molho.Molho')),
                ('pessoaEntregue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoaEntregue', to='pessoa.Pessoa')),
                ('pessoaRecebeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoaRecebeu', to='pessoa.Pessoa')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propriedade.Propriedade')),
            ],
        ),
    ]
