# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 11:16
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propriedade', '0001_initial'),
        ('molho', '0001_initial'),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrega', models.DateTimeField(verbose_name='Data Entrega')),
                ('dataPrevisaoRetorno', models.DateTimeField(verbose_name='Data de Previsão do Retorno')),
                ('dataRetorno', models.DateTimeField(blank=True, null=True, verbose_name='Data Retorno')),
                ('funcionario', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
                ('molhos', models.ManyToManyField(to='molho.Molho')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propriedade.Propriedade')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='pessoa.Pessoa')),
            ],
        ),
    ]
