# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='pessoaEntregue',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='pessoaRecebeu',
        ),
        migrations.AddField(
            model_name='registro',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='pessoa.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='pessoa.Pessoa'),
            preserve_default=False,
        ),
    ]
