# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20180201_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='pessoa.Pessoa'),
        ),
    ]
