# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0003_auto_20180201_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='registro',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
